{% set name = "coredis" %}
{% set version = "6.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coredis-{{ version }}.tar.gz
  sha256: 7293b4d8e0e85d9a06f19ef226ee83028356f920c74bd0e0ac604b9664f33769

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - mypy
    - packaging
    - hatchling
    - types-deprecated
    - hatch-vcs
    - pip
  run:
    - anyio >=4.11.0
    - exceptiongroup >=1.3.0
    - typing_extensions >=4.13
    - beartype >=0.20
    - python
    - async-timeout <6,>4
    - deprecated >=1.2
    - typing-extensions >=4.13
    - packaging >=21,<26
    - pympler >1,<2
    - wrapt >=1.1.0,<2

test:
  imports:
    - coredis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alisaifee/coredis
  summary: Python async client for Redis key-value store
  dev_url: https://github.com/alisaifee/coredis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
