{% set name = "coredis" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coredis-{{ version }}.tar.gz
  sha256: c312dc11b785367b2da440cba3ebd7a47ca0bbf673d74d923a590aa77550c73f

build:
  skip: true  # [win]
  skip: true  # [py<=39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - mypy
    - packaging >=21,<24
    - setuptools
    - types-deprecated
    - versioneer
    - pip
  run:
    - beartype >=0.20
    - python
    - async-timeout <6,>4
    - deprecated >=1.2
    - typing-extensions >=4.13
    - packaging >=21,<26
    - pympler >1,<2
    - wrapt >=1.1.0,<2

test:
  imports:
    - coredis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alisaifee/coredis
  summary: Python async client for Redis key-value store
  dev_url: https://github.com/alisaifee/coredis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
