{% set name = "coredis" %}
{% set version = "5.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coredis-{{ version }}.tar.gz
  sha256: 2b2f67e73a68bf4dc4d0d77b86ec7e03e75543f824f2f2bb076779ee9295bf65

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - mypy
    - packaging
    - hatchling
    - types-deprecated
    - hatch-vcs
    - pip
  run:
    - typing_extensions >=4.13
    - beartype >=0.20
    - python
    - async-timeout <6,>4
    - deprecated >=1.2
    - typing-extensions >=4.13
    - packaging >=21,<26
    - pympler >1,<2
    - wrapt >=1.1.0,<2

test:
  imports:
    - coredis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alisaifee/coredis
  summary: Python async client for Redis key-value store
  dev_url: https://github.com/alisaifee/coredis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
