{% set name = "coredis" %}
{% set version = "4.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coredis-{{ version }}.tar.gz
  sha256: bfd8566b169aa37b4f3ee11c9027f655d450ea3128a604df71702cf9f7daad6b

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - mypy
    - packaging >=21,<24
    - setuptools
    - types-deprecated
    - versioneer
    - pip
  run:
    - async_timeout >4,<6
    - python
    - async-timeout <6,>4
    - deprecated >=1.2
    - typing-extensions >=4.3
    - packaging >=21,<25
    - pympler >1,<2
    - wrapt >=1.1.0,<2

test:
  imports:
    - coredis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alisaifee/coredis
  summary: Python async client for Redis key-value store
  dev_url: https://github.com/alisaifee/coredis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
