schema_version: 1

context:
  name: coredis
  version: "6.6.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/coredis-${{ version }}.tar.gz
  sha256: 7d6dafc2dfb049ef5d835d5e98589fdd9e5ed0502e3caf34e1f0a9dc663b8704

build:
  number: 1
  skip: win
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - mypy
    - packaging
    - hatchling
    - types-deprecated
    - hatch-vcs
    - pip
  run:
    - opentelemetry-api >=1.0.0
    - anyio >=4.11.0
    - exceptiongroup >=1.3.0
    - typing_extensions >=4.13
    - beartype >=0.20
    - python
    - async-timeout <6,>4
    - deprecated >=1.2
    - typing-extensions >=4.13
    - packaging >=21,<27
    - pympler >1,<2
    - wrapt >=1.1.0,<2

tests:
  - python:
      imports:
        - coredis
      pip_check: true

about:
  summary: Python async client for Redis key-value store
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/alisaifee/coredis
  repository: https://github.com/alisaifee/coredis

extra:
  recipe-maintainers:
    - jan-janssen
